title: "Rustacean Station"
author: "Rustacean Station"
email: podcast@rustacean-station.org
subtitle: "A community project for creating podcast content for the Rust programming language."
description: "Come journey with us into the weird, wonderful, and wily world of Rust."
lang: en-us
exclude:
  - 000-template.md
  - vendor
  - audio
  - transcript_tools
collections:
  episodes:
    output: true
    permalink: /episode/:title/
  transcripts:
    output: true
    permalink: /transcript/:title/

# https://github.com/jekyll/jekyll/issues/7744
defaults:
 - scope:
     path: ""
     type: "episodes"
   values:
     layout: "episode"
 - scope:
     path: ""
     type: "transcripts"
   values:
     layout: "transcript"
