title: "Rustacean Station"
author: "Rustacean Station"
email: hello@rustacean-station.org
subtitle: "A Rust Meta-Podcast"
description: "Come journey with us into the weird, wonderful, and wily world of the Rust programming language."
lang: en-us
collections:
  episodes:
    output: true
    permalink: /episode/:title/

# https://github.com/jekyll/jekyll/issues/7744
defaults:
 - scope:
     path: ""
     type: "episodes"
   values:
     layout: "episode"
